# -*- coding: utf-8 -*-

class sap2012():
    """
    """
    
    def __init__(self):
        """
        """
        self.inputs={    
            'area':None,
            'average_storey_height':None,
            
            # ventilation_rates inputs
            'number_of_chimneys_main_heating':None,
            'number_of_chimneys_secondary_heating':None,
            'number_of_chimneys_other':None,
            'number_of_open_flues_main_heating':None,
            'number_of_open_flues_secondary_heating':None,
            'number_of_open_flues_other':None,
            'number_of_intermittant_fans_total':None,
            'number_of_passive_vents_total':None,
            'number_of_flueless_gas_fires_total':None,
            #### note that 'dwelling_volume' isn't needed as an input here because it is calculated in 'overall_dwelling_dimenstions' #### Please delete this line once read
            'air_permeability_value_q50':None,
            'number_of_storeys_in_the_dwelling':None,
            'structural_infiltration':None,
            'suspended_wooden_ground_floor_infiltration':None,
            'no_draft_lobby_infiltration':None,
            'percentage_of_windows_and_doors_draught_proofed':None,
            'number_of_sides_on_which_dwelling_is_sheltered':None,
            'monthly_average_wind_speed':None,
            'applicable_case':None,
            'mechanical_ventilation_air_change_rate_through_system':None,
            'exhaust_air_heat_pump_using_Appendix_N':None,
            'mechanical_ventilation_throughput_factor':None,
            'efficiency_allowing_for_in_use_factor':None,
            
            # heat_losses_and_heat_loss_parameter inputs
            'solid_door_net_area':None,
            'solid_door_u_value':None,
            'semi_glazed_door_net_area':None,
            'semi_glazed_door_u_value':None,
            'window_net_area':None,
            'window_u_value':None,
            'roof_window_net_area':None,
            'roof_window_u_value':None,
            'basement_floor_net_area':None,
            'basement_floor_u_value':None,
            'basement_floor_heat_capacity':None,
            'ground_floor_net_area':None,
            'ground_floor_u_value':None,
            'ground_floor_heat_capacity':None,
            'exposed_floor_net_area':None,
            'exposed_floor_u_value':None,
            'exposed_floor_heat_capacity':None,
            'basement_wall_gross_area':None,
            'basement_wall_opening':None,
            'basement_wall_u_value':None,
            'basement_wall_heat_capacity':None,
            'external_wall_gross_area':None,
            'external_wall_opening':None,
            'external_wall_u_value':None,
            'external_wall_heat_capacity':None,
            'roof_gross_area':None,
            'roof_opening':None,
            'roof_u_value':None,
            'roof_heat_capacity':None,
            'party_wall_net_area':None,
            'party_wall_u_value':None,
            'party_wall_heat_capacity':None,
            'party_floor_net_area':None,
            'party_floor_heat_capacity':None,
            'party_ceiling_net_area':None,
            'party_ceiling_heat_capacity':None,
            'internal_wall_net_area':None,
            'internal_wall_heat_capacity':None,
            'internal_floor_net_area':None,
            'internal_floor_heat_capacity':None,
            'internal_ceiling_net_area':None,
            'internal_ceiling_heat_capacity':None,
            'thermal_bridges_appendix_k':None,
            
            #water heating requirement inputs
            'assumed_occupancy':None,
            'V_dm_table_1c':None,
            'days_in_month':None,
            'T_table_1d':None,
            'water_storage_loss_manufacturer':None,
            'temperature_factor_table_2b':None,
            'storage_volume_litres':None,
            'hot_water_storage_loss_table_2':None,
            'volume_factor_table_2a':None,
            'Vs_appendix_G3':None,
            'solar_storage_WWHRS_factor':None,
            'primary_circuit_loss_table_3':None,
            'combi_loss_table_3':None,
            'solar_DHW_input_appendix_G':None,
            
            #internal gains inputs
            'metabolic_gains':None,
            'lighting_gains':None,
            'appliances_gains':None,
            'cooking_gains':None,
            'pumps_and_fans_gains':None,
            'losses':None,
            'water_heating_gains':None,
            
            #solar gains inputs
            'access_factor_table_6d_north':None,
            'access_factor_table_6d_north_east':None,
            'access_factor_table_6d_east':None,
            'access_factor_table_6d_south_east':None,
            'access_factor_table_6d_south':None,
            'access_factor_table_6d_south_west':None,
            'access_factor_table_6d_west':None,
            'access_factor_table_6d_north_west':None,
            'access_factor_table_6d_roof_windows':None,
            'area_north':None,
            'area_north_east':None,
            'area_east':None,
            'area_south_east':None,
            'area_south':None,
            'area_south_west':None,
            'area_west':None,
            'area_north_west':None,
            'area_roof_windows':None,
            'solar_flux_north':None,
            'solar_flux_north_east':None,
            'solar_flux_east':None,
            'solar_flux_south_east':None,
            'solar_flux_south':None,
            'solar_flux_south_west':None,
            'solar_flux_west':None,
            'solar_flux_north_west':None,
            'solar_flux_roof_windows':None,
            'g_table_6b_north':None,
            'g_table_6b_north_east':None,
            'g_table_6b_east':None,
            'g_table_6b_south_east':None,
            'g_table_6b_south':None,
            'g_table_6b_south_west':None,
            'g_table_6b_west':None,
            'g_table_6b_north_west':None,
            'g_table_6b_roof_windows':None,
            'FF_table_6b_north':None,
            'FF_table_6b_north_east':None,
            'FF_table_6b_east':None,
            'FF_table_6b_south_east':None,
            'FF_table_6b_south':None,
            'FF_table_6b_south_west':None,
            'FF_table_6b_west':None,
            'FF_table_6b_north_west':None,
            'FF_table_6b_roof_windows':None,
            
            #mean internal temperature inputs
            'temperature_during_heating_periods_living_room':None,
            'utilisation_factor_for_gains_living_room_table_9a':None,
            'mean_internal_temperature_living_room_T1_Table_9c':None,
            'temperature_during_heating_periods_rest_of_dwelling':None,
            'utilisation_factor_for_gains_rest_of_dwelling_table_9a':None,
            'mean_internal_temperature_rest_of_dwelling_T2_table_9c':None,
            'living_room_area':None,
            'temperature_adjustment_table_4e':None,
            
            #space heating requirement inputs
            'utilisation_factor_for_gains_table_9a':None,
            'total_gains_internal_and_solar':None,
            'monthly_external_temperature_table_U1':None,
            'mean_internal_temperature_whole_dwelling':None,
            
            #energy requirements inputs
            'fraction_of_space_heat_secondary_system':None,
            'fraction_of_space_heat_from_main_system_2':None,
            'efficiency_of_main_space_heating_system_1':None,
            'efficiency_of_main_space_heating_system_2':None,
            'efficiency_of_secondary_space_heating_system':None,
            'cooling_system_energy_efficiency_ratio_table_10c':None,
            'efficiency_of_water_heater_table_4a':None,
            'space_cooling_requirement_monthly':None,
            'electricity_demand_mechanical_ventilation_fans_table_4f':None,
            'electricity_demand_warm_air_heating_systems_fans_table_4f':None,
            'electricity_demand_central_heating_pump_or_water_pump_table_4f':None,
            'electricity_demand_oil_boiler_pump_table_4f':None,
            'electricity_demand_boiler_flue_fan_table_4f':None,
            'electricity_demand_keep_hot_facility_gas_combi_boiler_table_4f':None,
            'electricity_demand_pump_for_solar_water_heating_table_4f':None,
            'electricity_demand_pump_for_storage_WWHRS_Table_G3':None,
            'electricity_for_lighting':None,
            'electricity_generated_by_PV_Appendix_M':None,
            'electricity_generated_by_wind_turbine_appendix_M':None,
            'electricity_used_or_generated_by_micro_CHP_appendix_N':None,
            'electricity_generated_by_hydro_electric_generator_appendix_M':None,
            'appendix_Q_energy_saved':None,
            'appendix_Q_energy_used':None,
            
            #fuel cost inputs
            'space_heating_fuel_price_main_system_1':None,
            'space_heating_fuel_price_main_system_2':None,
            'space_heating_fuel_price_secondary':None,
            'water_heating_high_rate_fraction_table_13':None,
            'water_heating_low_rate_fraction_table_13':None,
            'high_rate_fuel_price':None,
            'low_rate_fuel_price':None,
            'water_heating_fuel_price_other':None,
            'space_cooling_fuel_used':None,
            'space_cooling_fuel_price':None,
            'electricity_for_pumps_fans_electric_keep_hot':None,
            'fuel_price_for_pumps_fans_electric_keep_hot':None,
            'fuel_price_for_lighting':None,
            'additional_standing_charges_table_12':None,
            'energy_saving_generation_technologies':None,
            'energy_saving_generation_technologies_fuel_price':None,
            'appendix_Q_energy_used_fuel_price':None,
            'appendix_Q_energy_saved_fuel_price':None,
            
            #Sap rating inputs
            'energy_cost_deflator':None,
            
            #CO2 emissions inputs
            'space_heating_fuel_emission_factor_main_system_1':None,
            'space_heating_fuel_emission_factor_main_system_2':None,
            'space_heating_fuel_emission_factor_secondary':None,
            'water_heating_fuel_emission_factor':None,
            'space_cooling_fuel_emission_factor':None,
            'fuel_emission_factor_for_pumps_fans_electric_keep_hot':None,
            'fuel_emission_factor_for_lighting':None,
            'energy_saving_generation_technologies_fuel_emission_factor':None,
            'appendix_Q_energy_used_fuel_emission_factor':None,
            'appendix_Q_energy_saved_fuel_emission_factor':None,
        }
        
        
        