# -*- coding: utf-8 -*-

from .temperature_reduction_when_heating_is_off_table_9b import temperature_reduction_when_heating_is_off_table_9b
from .utilisation_factor_for_heating_table_9a import utilisation_factor_for_heating_table_9a
from .heating_requirement_table_9c import heating_requirement_table_9c
from .utilisation_factor_for_heating_whole_house_table_9a import utilisation_factor_for_heating_whole_house_table_9a